In [1]:
import pandas as pd

In [3]:
flats=pd.read_csv('flats_cleaned.csv')
houses=pd.read_csv('house_cleaned.csv')

In [4]:
df=pd.concat([flats,houses],ignore_index=True)

In [5]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12.0,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2.0,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [6]:
df.sample(10)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
3019,4 Bedroom House for sale in Sector 48 Gurgaon,house,independent,8.40,25926.0,3240.0,Plot area 360(301.01 sq.m.),4,4,3,"pooja room,servant room","Sector 48 Gurgaon, Gurgaon, Haryana",2.0,NaN,10+ Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",It's 4bhk villa in posh society known as tatva...,"['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '5 Ge...","['Water Storage', 'Park', 'Piped-gas']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3416,2 Bedroom House for sale in Sohna,house,independent,1.55,14720.0,1053.0,Plot area 117(97.83 sq.m.),2,3,2,"pooja room,study room","Sohna, Gurgaon, Haryana",1.0,North,Within 3 months,NaN,"Check out this 2 bhk house for sale in sohna, ...","['6 Fan', '3 Geyser', '50 Light', '3 AC', '1 C...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
260,4 BHK Flat in Sector 1 Imt Manesar,flat,sonata group housing gh 24,1.65,5892.0,2800.0,Carpet area: 2800 (260.13 sq.m.),4,3,3,servant room,"Sector 1 Imt Manesar, Gurgaon, Haryana",8.0,NaN,0 to 1 Year Old,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",This 4 bhk flat is located in sonata group hou...,NaN,"['Lift(s)', 'Maintenance Staff', 'Water Storag...","['Environment5 out of 5', 'Safety4.5 out of 5'..."
1937,4 BHK Flat in Sector 91 Gurgaon,flat,tarc maceo,1.80,7758.0,2320.0,Carpet area: 2320 (215.54 sq.m.),4,3,3+,"pooja room,study room","Sector 91 Gurgaon, Gurgaon, Haryana",0.0,North,1 to 5 Year Old,"['Manish Gallexie 91', 'Dwarka Expressway', 'R...",Fully furnished property for sale,"['1 Water Purifier', '7 Fan', '1 Dining Table'...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction4 out of..."
3141,3 Bedroom House for sale in Rajendra Park,house,independent,0.60,13333.0,450.0,Built Up area: 450 (41.81 sq.m.),3,3,0,not available,"Rajendra Park, Sector 105, Rajendra Park, Gurg...",3.0,NaN,undefined,"['Palam Vihar Vyapar kendra', 'Chintapurni Man...",Best in class property available at rajendra p...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2321,3 BHK Flat in Shanti Nagar,flat,ganga apartment,0.74,6040.0,1225.0,Carpet area: 1225 (113.81 sq.m.),3,3,2,not available,"G-4, Shanti Nagar, Gurgaon, Haryana",0.0,North-East,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Hanuman Mandir', 'Stat...",Check out this 3 bhk apartment for sale in gan...,"['1 Modular Kitchen', '1 Chimney', '4 Wardrobe...","['Security / Fire Alarm', 'Lift(s)', 'High Cei...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2265,2 BHK Flat in Sector 76 Gurgaon,flat,suncity avenue 76,0.75,10204.0,735.0,Super Built up area 735(68.28 sq.m.),2,2,2,not available,"Sector 76 Gurgaon, Gurgaon, Haryana",11.0,NaN,By 2023,"['Omaxe Gurgaon Mall', 'Gurugram University', ...",We are the proud owners of this 2 bhk apartmen...,[],NaN,NaN
2292,3 BHK Flat in Sector 102 Gurgaon,flat,conscient heritage max,2.50,11633.0,2149.0,Super Built up area 2149(199.65 sq.m.),3,4,3+,"study room,servant room","B-2503, Sector 102 Gurgaon, Gurgaon, Haryana",25.0,North-East,0 to 1 Year Old,"['Huda Metro Station', 'Ocus Medley Mall', 'Th...",We are the proud owners of this 3 bhk apartmen...,"['4 Fan', '1 Exhaust Fan', '4 Geyser', '4 Ligh...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
2763,2 BHK Flat in Sector 95 Gurgaon,flat,ramsons kshitij,0.45,4591.0,980.0,Super Built up area 980(91.04 sq.m.),2,2,1,study room,"Sector 95 Gurgaon, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Bangali Clinic', 'Yadav Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk+study ro...,"['12 Fan', 'No AC', 'No Bed', 'No Chimney', 'N...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Management3.5 out of 5', 'Green Area4 out of..."
506,4 BHK Flat in Sector 72 Gurgaon,flat,tata primanti,4.25,13076.0,3250.0,Super Built up area 3250(301.93 sq.m.),4,4,3+,servant room,"Executive Apartment, Sector 72 Gurgaon, Gurgao...",0.0,North,1 to 5 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...",This lovely 4 bhk apartment/flat in sector 72 ...,"['6 Wardrobe', '1 Water Purifier', '10 Fan', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."

In [7]:
df.shape

(3961, 20)

In [8]:
df.to_csv('gurugram_properties.csv',index=False)