In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('gurgaon_properties_post_feature_selection.csv')

In [3]:
df.head()

,property_type,sector,bedRoom,bathroom,balcony,facing,built_up_area,servant room,age_category,furnishing_type,combined_rating,luxury_category,floor_category,price
0,0.0,72.0,2,2,1.0,7.0,1000.0,0,3.0,2.0,4.00,0.0,2.0,0.45
1,0.0,32.0,2,2,1.0,7.0,722.0,0,2.0,0.0,4.25,0.0,1.0,0.50
2,0.0,100.0,2,2,3.0,0.0,661.0,0,1.0,2.0,4.25,0.0,0.0,0.40
3,0.0,64.0,2,2,2.0,0.0,1333.0,0,3.0,2.0,4.20,0.0,1.0,1.47
4,0.0,96.0,2,2,3.0,0.0,1217.0,0,4.0,2.0,4.00,0.0,2.0,0.70

In [4]:
X = df.drop(columns=['price'])
y = df['price']

In [ ]:
# 1. ohe
# 2. scale and transform price (log)
# 3. model train

In [6]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.svm import SVR

In [7]:
df.head(1)

,property_type,sector,bedRoom,bathroom,balcony,facing,built_up_area,servant room,age_category,furnishing_type,combined_rating,luxury_category,floor_category,price
0,0.0,72.0,2,2,1.0,7.0,1000.0,0,3.0,2.0,4.0,0.0,2.0,0.45

In [8]:
columns_to_encode = ['sector', 'balcony', 'age_category', 'facing','furnishing_type', 'luxury_category', 'floor_category']

In [9]:
# Applying the log1p transformation to the target variable
y_transformed = np.log1p(y)

In [13]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['property_type', 'bedRoom', 'bathroom', 'built_up_area', 'servant room', 'combined_rating']),
        ('cat', OneHotEncoder(drop='first'), columns_to_encode)
    ], 
    remainder='passthrough'
)

In [23]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    # ('regressor', LinearRegression())
    ('regressor', SVR(kernel='rbf'))

])

In [24]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [25]:
scores.mean()

np.float64(0.8833208024763713)

In [26]:
scores.std()

np.float64(0.01838979741256131)

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [28]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['property_type', 'bedRoom',
                                                   'bathroom', 'built_up_area',
                                                   'servant room',
                                                   'combined_rating']),
                                                 ('cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['sector', 'balcony',
                                                   'age_category', 'facing',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category'])])),
                ('regressor', SVR())])

In [29]:
y_pred=pipeline.predict(X_test)

In [30]:
y_pred=np.expm1(y_pred)

In [31]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(np.expm1(y_test),y_pred)

0.5422805197743026

In [32]:
# my experimentation

In [37]:
from sklearn.model_selection import KFold, cross_val_predict
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, mean_absolute_error

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    GradientBoostingRegressor,
    AdaBoostRegressor
)
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

import numpy as np

models = {
    "Linear Regression": LinearRegression(),
    "Ridge": Ridge(random_state=42),
    "Lasso": Lasso(random_state=42),
    "ElasticNet": ElasticNet(random_state=42),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42),
    "Extra Trees": ExtraTreesRegressor(random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(random_state=42),
    "AdaBoost": AdaBoostRegressor(random_state=42),
    "KNN": KNeighborsRegressor(),
    "SVR": SVR(),

    # Boosting Models
    "XGBoost": XGBRegressor(
        random_state=42,
        verbosity=0
    ),

    "LightGBM": LGBMRegressor(
        random_state=42,
        verbose=-1
    ),

    "CatBoost": CatBoostRegressor(
        random_state=42,
        verbose=0
    )
}

kfold = KFold(n_splits=10, shuffle=True, random_state=42)

print(f'{"Model":25} {"R² Score":10} {"MAE":10}')
print("-"*50)

for name, model in models.items():

    pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("model", model)
    ])

    y_pred_log = cross_val_predict(
        pipeline,
        X,
        y_transformed,
        cv=kfold,
        n_jobs=-1
    )

    r2 = r2_score(y_transformed, y_pred_log)

    y_true = np.expm1(y_transformed)
    y_pred = np.expm1(y_pred_log)

    mae = mean_absolute_error(y_true, y_pred)

    print(f"{name:25} {r2:.4f}     {mae:.4f}")

Model                     R² Score   MAE
--------------------------------------------------
Linear Regression         0.8358     0.6899
Ridge                     0.8364     0.6914
Lasso                     -0.0006     1.5832
ElasticNet                -0.0006     1.5832
Decision Tree             0.7933     0.6716
Random Forest             0.8806     0.5291
Extra Trees               0.8861     0.5112
Gradient Boosting         0.8610     0.6184
AdaBoost                  0.7213     0.9281
KNN                       0.8174     0.6778
SVR                       0.8845     0.5406
XGBoost                   0.8905     0.5155
LightGBM                  0.8778     0.5595

CatBoostError: catboost/libs/train_lib/dir_helper.cpp:26: Can't create train tmp dir: tmp

In [36]:
!pip install xgboost lightgbm catboost

Collecting xgboost
  Downloading xgboost-3.3.0-py3-none-win_amd64.whl.metadata (2.0 kB)
Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Collecting catboost
  Downloading catboost-1.2.10-cp314-cp314-win_amd64.whl.metadata (1.5 kB)
Requirement already satisfied: numpy in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from xgboost) (2.4.4)
Requirement already satisfied: scipy in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from xgboost) (1.17.1)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from catboost) (3.10.8)
Requirement already satisfied: pandas<4.0,>=0.24 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from catboost) (3.0.2)
Requirement already satisfied: plotly in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from catboost) (6.6.0)
Requirement already satisfied: six in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib->catboost) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib->catboost) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from plotly->catboost) (2.18.1)
Downloading xgboost-3.3.0-py3-none-win_amd64.whl (69.5 MB)
   ---------------------------------------- 0.0/69.5 MB ? eta -:--:--
   ---------------------------------------- 0.8/69.5 MB 5.6 MB/s eta 0:00:13
    --------------------------------------- 1.6/69.5 MB 4.3 MB/s eta 0:00:16
   - -------------------------------------- 2.1/69.5 MB 4.4 MB/s eta 0:00:16
   - -------------------------------------- 2.9/69.5 MB 3.8 MB/s eta 0:00:18
   -- ------------------------------------- 3.9/69.5 MB 4.0 MB/s eta 0:00:17
   -- ------------------------------------- 5.0/69.5 MB 4.1 MB/s eta 0:00:16
   --- ------------------------------------ 6.0/69.5 MB 4.2 MB/s eta 0:00:16
   ---- ----------------------------------- 7.1/69.5 MB 4.3 MB/s eta 0:00:15
   ---- ----------------------------------- 7.9/69.5 MB 4.3 MB/s eta 0:00:15
   ----- ---------------------------------- 8.9/69.5 MB 4.3 MB/s eta 0:00:15
   ----- ---------------------------------- 9.7/69.5 MB 4.2 MB/s eta 0:00:15
   ------ --------------------------------- 10.5/69.5 MB 4.2 MB/s eta 0:00:15
   ------ --------------------------------- 11.3/69.5 MB 4.2 MB/s eta 0:00:14
   ------- -------------------------------- 12.3/69.5 MB 4.2 MB/s eta 0:00:14
   ------- -------------------------------- 13.1/69.5 MB 4.2 MB/s eta 0:00:14
   -------- ------------------------------- 14.2/69.5 MB 4.2 MB/s eta 0:00:14
   -------- ------------------------------- 14.9/69.5 MB 4.2 MB/s eta 0:00:14
   --------- ------------------------------ 15.7/69.5 MB 4.2 MB/s eta 0:00:13
   --------- ------------------------------ 16.5/69.5 MB 4.2 MB/s eta 0:00:13
   ---------- ----------------------------- 17.6/69.5 MB 4.2 MB/s eta 0:00:13
   ---------- ----------------------------- 18.4/69.5 MB 4.2 MB/s eta 0:00:13
   ----------- ---------------------------- 19.4/69.5 MB 4.2 MB/s eta 0:00:12
   ----------- ---------------------------- 20.2/69.5 MB 4.2 MB/s eta 0:00:12
   ------------ --------------------------- 21.0/69.5 MB 4.2 MB/s eta 0:00:12
   ------------ --------------------------- 22.0/69.5 MB 4.2 MB/s eta 0:00:12
   ------------ --------------------------- 22.5/69.5 MB 4.2 MB/s eta 0:00:12
   ------------- -------------------------- 23.6/69.5 MB 4.2 MB/s eta 0:00:11
   -------------- ------------------------- 24.4/69.5 MB 4.2 MB/s eta 0:00:11
   -------------- ------------------------- 25.2/69.5 MB 4.2 MB/s eta 0:00:11
   -------------- ------------------------- 26.0/69.5 MB 4.2 MB/s eta 0:00:11
   --------------- ------------------------ 26.7/69.5 MB 4.1 MB/s eta 0:00:11
   --------------- ------------------------ 27.3/69.5 MB 4.1 MB/s eta 0:00:11
   --------------- ------------------------ 27.3/69.5 MB 4.1 MB/s eta 0:00:11
   --------------- ------------------------ 27.8/69.5 MB 3.9 MB/s eta 0:00:11
   ---------------- ----------------------- 28.6/69.5 MB 3.9 MB/s eta 0:00:11
   ---------------- ----------------------- 29.4/69.5 MB 3.9 MB/s eta 0:00:11
   ----------------- ---------------------- 30.4/69.5 MB 3.9 MB/s eta 0:00:10
   ----------------- ---------------------- 31.2/69.5 MB 3.9 MB/s eta 0:00:10
   ------------------ --------------------- 31.5/69.5 MB 3.9 MB/s eta 0:00:10
   ------------------ --------------------- 32.2/69.5 MB 3.8 MB/s eta 0:00:10
   ------------------ --------------------- 32.5/69.5 MB 3.8 MB/s eta 0:00:10
   ------------------ --------------------- 32.5/69.5 MB 3.8 MB/s eta 0:00:10
   ------------------ --------------------- 32.5/69.5 MB 3.8 MB/s eta 0:00:10
   ------------------ --------------------- 32.5/69.5 MB 3.8 MB/s eta 0:00:10
   ------------------- -------------------- 33.0/69.5 MB 3.5 MB/s eta 0:00:11
   ------------------- -------------------- 33.6/69.5 MB 3.5 MB/s eta 0:00:11
   ------------------- -------------------- 34.3/69.5 MB 3.5 MB/s eta 0:00:11
   -------------------- ------------------- 35.4/69.5 MB 3.5 MB/s eta 0:00:10
   -------------------- ------------------- 35.9/69.5 MB 3.5 MB/s eta 0:00:10
   --------------------- ------------------ 36.7/69.5 MB 3.5 MB/s eta 0:00:10
   --------------------- ------------------ 37.5/69.5 MB 3.5 MB/s eta 0:00:10
   ---------------------- ----------------- 38.5/69.5 MB 3.5 MB/s eta 0:00:09
   ---------------------- ----------------- 39.3/69.5 MB 3.5 MB/s eta 0:00:09
   ----------------------- ---------------- 40.4/69.5 MB 3.6 MB/s eta 0:00:09
   ----------------------- ---------------- 40.9/69.5 MB 3.6 MB/s eta 0:00:09
   ----------------------- ---------------- 41.4/69.5 MB 3.5 MB/s eta 0:00:08
   ------------------------ --------------- 42.2/69.5 MB 3.5 MB/s eta 0:00:08
   ------------------------ --------------- 43.0/69.5 MB 3.5 MB/s eta 0:00:08
   ------------------------- -------------- 43.8/69.5 MB 3.5 MB/s eta 0:00:08
   ------------------------- -------------- 44.8/69.5 MB 3.5 MB/s eta 0:00:07
   -------------------------- ------------- 45.6/69.5 MB 3.6 MB/s eta 0:00:07
   -------------------------- ------------- 46.4/69.5 MB 3.6 MB/s eta 0:00:07
   --------------------------- ------------ 47.2/69.5 MB 3.6 MB/s eta 0:00:07
   --------------------------- ------------ 47.7/69.5 MB 3.5 MB/s eta 0:00:07
   ---------------------------- ----------- 48.8/69.5 MB 3.6 MB/s eta 0:00:06
   ---------------------------- ----------- 49.5/69.5 MB 3.6 MB/s eta 0:00:06
   ---------------------------- ----------- 50.3/69.5 MB 3.6 MB/s eta 0:00:06
   ----------------------------- ---------- 51.1/69.5 MB 3.6 MB/s eta 0:00:06
   ----------------------------- ---------- 51.9/69.5 MB 3.6 MB/s eta 0:00:05
   ------------------------------ --------- 53.2/69.5 MB 3.6 MB/s eta 0:00:05
   ------------------------------- -------- 54.0/69.5 MB 3.6 MB/s eta 0:00:05
   ------------------------------- -------- 55.1/69.5 MB 3.6 MB/s eta 0:00:04
   -------------------------------- ------- 55.8/69.5 MB 3.6 MB/s eta 0:00:04
   -------------------------------- ------- 56.6/69.5 MB 3.7 MB/s eta 0:00:04
   -------------------------------- ------- 56.6/69.5 MB 3.7 MB/s eta 0:00:04
   --------------------------------- ------ 57.4/69.5 MB 3.6 MB/s eta 0:00:04
   --------------------------------- ------ 57.7/69.5 MB 3.6 MB/s eta 0:00:04
   --------------------------------- ------ 58.5/69.5 MB 3.6 MB/s eta 0:00:04
   --------------------------------- ------ 59.0/69.5 MB 3.6 MB/s eta 0:00:03
   ---------------------------------- ----- 59.5/69.5 MB 3.5 MB/s eta 0:00:03
   ---------------------------------- ----- 60.0/69.5 MB 3.5 MB/s eta 0:00:03
   ---------------------------------- ----- 60.8/69.5 MB 3.5 MB/s eta 0:00:03
   ----------------------------------- ---- 61.3/69.5 MB 3.5 MB/s eta 0:00:03
   ----------------------------------- ---- 62.1/69.5 MB 3.5 MB/s eta 0:00:03
   ------------------------------------ --- 62.9/69.5 MB 3.5 MB/s eta 0:00:02
   ------------------------------------ --- 63.4/69.5 MB 3.5 MB/s eta 0:00:02
   ------------------------------------ --- 64.2/69.5 MB 3.5 MB/s eta 0:00:02
   ------------------------------------- -- 65.0/69.5 MB 3.5 MB/s eta 0:00:02
   ------------------------------------- -- 65.5/69.5 MB 3.5 MB/s eta 0:00:02
   -------------------------------------- - 66.3/69.5 MB 3.5 MB/s eta 0:00:01
   -------------------------------------- - 67.1/69.5 MB 3.5 MB/s eta 0:00:01
   -------------------------------------- - 67.4/69.5 MB 3.5 MB/s eta 0:00:01
   -------------------------------------- - 67.4/69.5 MB 3.5 MB/s eta 0:00:01
   -------------------------------------- - 67.6/69.5 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  68.4/69.5 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  68.7/69.5 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 69.5/69.5 MB 3.4 MB/s  0:00:20
Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   -------------- ------------------------- 0.5/1.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------- ----------- 1.0/1.5 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 2.5 MB/s  0:00:00
Downloading catboost-1.2.10-cp314-cp314-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/101.7 MB 2.5 MB/s eta 0:00:41
   ---------------------------------------- 1.0/101.7 MB 2.5 MB/s eta 0:00:40
    --------------------------------------- 1.3/101.7 MB 2.1 MB/s eta 0:00:48
    --------------------------------------- 1.3/101.7 MB 2.1 MB/s eta 0:00:48
    --------------------------------------- 1.3/101.7 MB 2.1 MB/s eta 0:00:48
    --------------------------------------- 1.8/101.7 MB 1.3 MB/s eta 0:01:16
    --------------------------------------- 2.1/101.7 MB 1.4 MB/s eta 0:01:12
    --------------------------------------- 2.1/101.7 MB 1.4 MB/s eta 0:01:12
   - -------------------------------------- 2.6/101.7 MB 1.3 MB/s eta 0:01:15
   - -------------------------------------- 2.9/101.7 MB 1.3 MB/s eta 0:01:14
   - -------------------------------------- 3.1/101.7 MB 1.4 MB/s eta 0:01:12
   - -------------------------------------- 3.7/101.7 MB 1.4 MB/s eta 0:01:09
   - -------------------------------------- 3.9/101.7 MB 1.4 MB/s eta 0:01:08
   - -------------------------------------- 4.5/101.7 MB 1.5 MB/s eta 0:01:06
   - -------------------------------------- 5.0/101.7 MB 1.5 MB/s eta 0:01:03
   -- ------------------------------------- 5.2/101.7 MB 1.6 MB/s eta 0:01:02
   -- ------------------------------------- 5.2/101.7 MB 1.6 MB/s eta 0:01:02
   -- ------------------------------------- 5.5/101.7 MB 1.4 MB/s eta 0:01:08
   -- ------------------------------------- 6.0/101.7 MB 1.5 MB/s eta 0:01:05
   -- ------------------------------------- 6.3/101.7 MB 1.5 MB/s eta 0:01:04
   -- ------------------------------------- 6.8/101.7 MB 1.5 MB/s eta 0:01:04
   -- ------------------------------------- 7.1/101.7 MB 1.5 MB/s eta 0:01:04
   -- ------------------------------------- 7.6/101.7 MB 1.5 MB/s eta 0:01:03
   --- ------------------------------------ 8.1/101.7 MB 1.6 MB/s eta 0:01:00
   --- ------------------------------------ 8.4/101.7 MB 1.6 MB/s eta 0:00:59
   --- ------------------------------------ 8.4/101.7 MB 1.6 MB/s eta 0:00:59
   --- ------------------------------------ 8.7/101.7 MB 1.5 MB/s eta 0:01:04
   --- ------------------------------------ 8.9/101.7 MB 1.5 MB/s eta 0:01:03
   --- ------------------------------------ 8.9/101.7 MB 1.5 MB/s eta 0:01:03
   --- ------------------------------------ 9.2/101.7 MB 1.4 MB/s eta 0:01:05
   --- ------------------------------------ 9.4/101.7 MB 1.4 MB/s eta 0:01:06
   --- ------------------------------------ 10.0/101.7 MB 1.4 MB/s eta 0:01:04
   --- ------------------------------------ 10.0/101.7 MB 1.4 MB/s eta 0:01:04
   ---- ----------------------------------- 10.2/101.7 MB 1.4 MB/s eta 0:01:06
   ---- ----------------------------------- 10.5/101.7 MB 1.4 MB/s eta 0:01:06
   ---- ----------------------------------- 10.5/101.7 MB 1.4 MB/s eta 0:01:06
   ---- ----------------------------------- 10.5/101.7 MB 1.4 MB/s eta 0:01:06
   ---- ----------------------------------- 10.5/101.7 MB 1.4 MB/s eta 0:01:06
   ---- ----------------------------------- 10.5/101.7 MB 1.4 MB/s eta 0:01:06
   ---- ----------------------------------- 10.5/101.7 MB 1.4 MB/s eta 0:01:06
   ---- ----------------------------------- 10.5/101.7 MB 1.4 MB/s eta 0:01:06
   ---- ----------------------------------- 10.7/101.7 MB 1.2 MB/s eta 0:01:17
   ---- ----------------------------------- 10.7/101.7 MB 1.2 MB/s eta 0:01:17
   ---- ----------------------------------- 10.7/101.7 MB 1.2 MB/s eta 0:01:17
   ---- ----------------------------------- 10.7/101.7 MB 1.2 MB/s eta 0:01:17
   ---- ----------------------------------- 10.7/101.7 MB 1.2 MB/s eta 0:01:17
   ---- ----------------------------------- 10.7/101.7 MB 1.2 MB/s eta 0:01:17
   ---- ----------------------------------- 10.7/101.7 MB 1.2 MB/s eta 0:01:17
   ---- ----------------------------------- 10.7/101.7 MB 1.2 MB/s eta 0:01:17
   ---- ----------------------------------- 11.0/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ----------------------------------- 11.0/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ----------------------------------- 11.0/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ----------------------------------- 11.0/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ----------------------------------- 11.0/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ----------------------------------- 11.0/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ----------------------------------- 11.0/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ----------------------------------- 11.0/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ----------------------------------- 11.0/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ----------------------------------- 11.0/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ----------------------------------- 11.0/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ----------------------------------- 11.0/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ----------------------------------- 11.0/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ----------------------------------- 11.0/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ----------------------------------- 11.0/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ---------------------------------- 11.3/101.7 MB 805.9 kB/s eta 0:01:53
   ---- ---------------------------------- 11.3/101.7 MB 805.9 kB/s eta 0:01:53
   ---- ---------------------------------- 11.5/101.7 MB 799.9 kB/s eta 0:01:53
   ---- ---------------------------------- 12.3/101.7 MB 836.1 kB/s eta 0:01:47
   ---- ---------------------------------- 12.6/101.7 MB 845.5 kB/s eta 0:01:46
   ----- --------------------------------- 13.4/101.7 MB 883.9 kB/s eta 0:01:40
   ----- --------------------------------- 13.6/101.7 MB 896.3 kB/s eta 0:01:39
   ----- --------------------------------- 14.4/101.7 MB 926.1 kB/s eta 0:01:35
   ----- --------------------------------- 15.2/101.7 MB 964.1 kB/s eta 0:01:30
   ------ -------------------------------- 15.7/101.7 MB 987.9 kB/s eta 0:01:28
   ------ --------------------------------- 16.3/101.7 MB 1.0 MB/s eta 0:01:26
   ------ --------------------------------- 16.8/101.7 MB 1.0 MB/s eta 0:01:23
   ------ --------------------------------- 17.0/101.7 MB 1.0 MB/s eta 0:01:23
   ------- -------------------------------- 17.8/101.7 MB 1.1 MB/s eta 0:01:19
   ------- -------------------------------- 18.1/101.7 MB 1.1 MB/s eta 0:01:19
   ------- -------------------------------- 18.6/101.7 MB 1.1 MB/s eta 0:01:17
   ------- -------------------------------- 19.1/101.7 MB 1.1 MB/s eta 0:01:16
   ------- -------------------------------- 19.9/101.7 MB 1.1 MB/s eta 0:01:13
   ------- -------------------------------- 19.9/101.7 MB 1.1 MB/s eta 0:01:13
   -------- ------------------------------- 21.0/101.7 MB 1.2 MB/s eta 0:01:10
   -------- ------------------------------- 21.0/101.7 MB 1.2 MB/s eta 0:01:10
   -------- ------------------------------- 21.5/101.7 MB 1.2 MB/s eta 0:01:09
   -------- ------------------------------- 22.0/101.7 MB 1.2 MB/s eta 0:01:08
   -------- ------------------------------- 22.5/101.7 MB 1.2 MB/s eta 0:01:07
   --------- ------------------------------ 23.1/101.7 MB 1.2 MB/s eta 0:01:05
   --------- ------------------------------ 23.3/101.7 MB 1.2 MB/s eta 0:01:05
   --------- ------------------------------ 24.1/101.7 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 24.1/101.7 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 24.1/101.7 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 24.1/101.7 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 24.1/101.7 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 24.1/101.7 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 24.1/101.7 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 24.1/101.7 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 24.1/101.7 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 24.1/101.7 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 24.1/101.7 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 24.1/101.7 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 25.2/101.7 MB 1.1 MB/s eta 0:01:08
   --------- ------------------------------ 25.2/101.7 MB 1.1 MB/s eta 0:01:08
   --------- ------------------------------ 25.2/101.7 MB 1.1 MB/s eta 0:01:08
   --------- ------------------------------ 25.2/101.7 MB 1.1 MB/s eta 0:01:08
   --------- ------------------------------ 25.2/101.7 MB 1.1 MB/s eta 0:01:08
   --------- ------------------------------ 25.2/101.7 MB 1.1 MB/s eta 0:01:08
   --------- ------------------------------ 25.2/101.7 MB 1.1 MB/s eta 0:01:08
   ---------- ----------------------------- 26.0/101.7 MB 1.1 MB/s eta 0:01:09
   ---------- ----------------------------- 26.2/101.7 MB 1.1 MB/s eta 0:01:08
   ---------- ----------------------------- 26.7/101.7 MB 1.1 MB/s eta 0:01:08
   ---------- ----------------------------- 27.3/101.7 MB 1.1 MB/s eta 0:01:06

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [39]:
# picking -  
# 1. Random RandomForest
# 2. Extra trees
# 3. SVR
# 4. xgboost

1. RANDOM FOREST

In [40]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=42)

pipe = Pipeline([
    ("model", rf)
])

In [41]:
param_dist = {

    "model__n_estimators":[100,200,300,500,800,1000],

    "model__max_depth":[
        None,5,10,15,20,30,40,50
    ],

    "model__min_samples_split":[
        2,5,10,15,20
    ],

    "model__min_samples_leaf":[
        1,2,4,6,8
    ],

    "model__max_features":[
        "sqrt",
        "log2",
        0.5,
        0.7,
        None
    ],

    "model__bootstrap":[
        True,
        False
    ]
}

In [42]:
from sklearn.model_selection import RandomizedSearchCV

random_search = RandomizedSearchCV(

    estimator=pipe,

    param_distributions=param_dist,

    n_iter=100,

    cv=10,

    scoring='r2',

    verbose=2,

    random_state=42,

    n_jobs=-1

)

random_search.fit(X,y_transformed)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits

RandomizedSearchCV(cv=10,
                   estimator=Pipeline(steps=[('model',
                                              RandomForestRegressor(random_state=42))]),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'model__bootstrap': [True, False],
                                        'model__max_depth': [None, 5, 10, 15,
                                                             20, 30, 40, 50],
                                        'model__max_features': ['sqrt', 'log2',
                                                                0.5, 0.7,
                                                                None],
                                        'model__min_samples_leaf': [1, 2, 4, 6,
                                                                    8],
                                        'model__min_samples_split': [2, 5, 10,
                                                                     15, 20],
                                        'model__n_estimators': [100, 200, 300,
                                                                500, 800,
                                                                1000]},
                   random_state=42, scoring='r2', verbose=2)

In [43]:
print(random_search.best_score_)

print(random_search.best_params_)

0.8431333213433021
{'model__n_estimators': 1000, 'model__min_samples_split': 2, 'model__min_samples_leaf': 1, 'model__max_features': 0.5, 'model__max_depth': 40, 'model__bootstrap': False}

In [ ]:
# 0.8431333213433021
# {'model__n_estimators': 1000, 'model__min_samples_split': 2, 'model__min_samples_leaf': 1, 'model__max_features': 0.5, 'model__max_depth': 40, 'model__bootstrap': False}

2. EXTRA_TREES

In [44]:
from sklearn.ensemble import ExtraTreesRegressor

pipe_extree = Pipeline([
    ("model",ExtraTreesRegressor(random_state=42))
])

In [46]:
param_dist_extree={

'model__n_estimators':[200,400,600,800,1000],

'model__max_depth':[None,10,20,30,40,50],

'model__min_samples_split':[2,5,10],

'model__min_samples_leaf':[1,2,4],

'model__max_features':[
"sqrt",
"log2",
0.5,
0.7,
None
]

}

In [47]:
from sklearn.model_selection import RandomizedSearchCV

random_search = RandomizedSearchCV(

    estimator=pipe_extree,

    param_distributions=param_dist_extree,

    n_iter=100,

    cv=10,

    scoring='r2',

    verbose=10,

    random_state=42,

    n_jobs=-1

)

random_search.fit(X,y_transformed)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits

RandomizedSearchCV(cv=10,
                   estimator=Pipeline(steps=[('model',
                                              ExtraTreesRegressor(random_state=42))]),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'model__max_depth': [None, 10, 20, 30,
                                                             40, 50],
                                        'model__max_features': ['sqrt', 'log2',
                                                                0.5, 0.7,
                                                                None],
                                        'model__min_samples_leaf': [1, 2, 4],
                                        'model__min_samples_split': [2, 5, 10],
                                        'model__n_estimators': [200, 400, 600,
                                                                800, 1000]},
                   random_state=42, scoring='r2', verbose=10)

In [49]:
print(random_search.best_score_)

print(random_search.best_params_)

0.8208493483303279
{'model__n_estimators': 600, 'model__min_samples_split': 2, 'model__min_samples_leaf': 1, 'model__max_features': None, 'model__max_depth': 50}